jobs:
  - name: dv-man-job2
    type: manifest
    steps:
      - IN: dv-image-job2
        pull: false
      - IN: dv-opts-job2
      - IN: dv-params-job2
        applyTo:
          - dv-image-job2
      - TASK: managed
      - IN: trigger-dv-man-job2
    on_success:
      - echo 'this is on_success step of dv-man of type manifest'
    on_failure:
      - echo 'this is on_failure step of dv-man of type manifest'
